; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed-xiao-afruitnrf52-nrf52840-sense-plus]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense-plus
framework = arduino

; Velocidade monitor serial
monitor_speed = 115200

; Bibliotecas necessárias
lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3
	sparkfun/SparkFun u-blox GNSS Arduino Library
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    adafruit/Adafruit SSD1351 library
    adafruit/Adafruit GFX Library
	jgromes/RadioLib
    rweather/Crypto
    adafruit/Adafruit SPIFlash



; Configuração I2C (fix para Xiao)
build_flags =
    -DARDUINO_ARCH_NRF52
    -DUSE_TINYUSB
    ;-DPIN_WIRE_SDA=4
    ;-DPIN_WIRE_SCL=5

; Upload settings
upload_protocol = nrfutil
