"""unique constraint em medication_adherence

Revision ID: 09f7da2ef011
Revises: daaeabc42ec5
Create Date: 2026-07-10 11:17:13.370913

Corrige `MedicationAdherence`, que só tinha um Index não-único em
(medication_id, scheduled_datetime) — nada na BD impedia duas linhas para a
mesma dose agendada, apesar do endpoint `POST /api/medications/{id}/adherence`
(bridge/api.py) documentar essa combinação como idempotente. Ver o comentário
em `MedicationAdherence.__table_args__` (storage_advanced.py) para a
reprodução concreta do bug (corrida entre o SELECT e o INSERT desse
endpoint) e o tratamento de `IntegrityError` adicionado ao próprio endpoint
para recuperar dessa corrida sem devolver 500.

AVISO (não testado contra dados reais, protótipo sem BD em produção ainda —
ver PROJECT_STATUS.md): se esta migração correr contra uma instância que já
tenha duplicados genuínos (criados antes desta correção, pela própria
condição de corrida aqui corrigida), `create_unique_constraint` abaixo falha
até esses duplicados serem resolvidos manualmente (decidir qual linha manter
por dose). Não incluído aqui um passo de deduplicação automática porque não
há forma segura de decidir automaticamente qual das linhas duplicadas é a
"boa" sem contexto humano (ex.: qual `taken`/`method` reflete a realidade).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f7da2ef011'
down_revision: Union[str, Sequence[str], None] = 'daaeabc42ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_adherence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_adherence_medication_scheduled'))
        batch_op.create_unique_constraint('uq_adherence_medication_scheduled', ['medication_id', 'scheduled_datetime'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_adherence', schema=None) as batch_op:
        batch_op.drop_constraint('uq_adherence_medication_scheduled', type_='unique')
        batch_op.create_index(batch_op.f('idx_adherence_medication_scheduled'), ['medication_id', 'scheduled_datetime'], unique=False)

    # ### end Alembic commands ###
