"""schema inicial

Revision ID: daaeabc42ec5
Revises: 
Create Date: 2026-07-07 16:15:32.278176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daaeabc42ec5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('nif_encrypted', sa.String(length=512), nullable=True),
    sa.Column('address_encrypted', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patient_uuid', ['uuid'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('professional_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_audit_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'scope', 'version', name='uq_consent_patient_scope_version')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_variant', sa.String(length=100), nullable=True),
    sa.Column('battery_percent', sa.Integer(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('storage_used_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_total_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('idx_device_patient_id', ['patient_id'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('prescribed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('patient_caregivers',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view_alerts', sa.Boolean(), nullable=True),
    sa.Column('can_edit_notes', sa.Boolean(), nullable=True),
    sa.Column('can_edit_medications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'user_id')
    )
    op.create_table('personalized_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('heart_rate_min', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('spo2_min', sa.Integer(), nullable=True),
    sa.Column('inactivity_threshold_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_target_minutes', sa.Integer(), nullable=True),
    sa.Column('activity_target_minutes', sa.Integer(), nullable=True),
    sa.Column('steps_target_daily', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('activity_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('activity_category', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_windows', schema=None) as batch_op:
        batch_op.create_index('idx_activity_device_date', ['device_id', 'activity_date'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('read_by_user_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('silenced', sa.Boolean(), nullable=True),
    sa.Column('silenced_until', sa.DateTime(), nullable=True),
    sa.Column('escalated_to_severity', sa.String(length=20), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['read_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_device_created', ['device_id', 'created_at'], unique=False)
        batch_op.create_index('idx_alert_severity_read', ['severity', 'read_at'], unique=False)

    op.create_table('anomaly_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('potential_cause', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('investigated', sa.Boolean(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_detections', schema=None) as batch_op:
        batch_op.create_index('idx_anomaly_device_datetime', ['device_id', 'start_datetime'], unique=False)

    op.create_table('daily_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.DateTime(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('min_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('avg_spo2', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('activity_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rest_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('eating_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('hygiene_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('alerts_count', sa.Integer(), nullable=True),
    sa.Column('anomalies_count', sa.Integer(), nullable=True),
    sa.Column('medication_adherence_percent', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'stat_date', name='uq_daily_stats_device_date')
    )
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.create_index('idx_daily_stats_device_date', ['device_id', 'stat_date'], unique=False)

    op.create_table('emergency_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('timestamp_utc', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_user_id', sa.Integer(), nullable=True),
    sa.Column('response_action', sa.String(length=50), nullable=True),
    sa.Column('confirmation_code', sa.String(length=6), nullable=True),
    sa.Column('confirmation_attempts', sa.Integer(), nullable=True),
    sa.Column('confirmation_blocked_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['response_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sequence_number', name='uq_emergency_device_seq'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_emergency_device_timestamp', ['device_id', 'timestamp_utc'], unique=False)
        batch_op.create_index('idx_emergency_responded', ['responded_at'], unique=False)

    op.create_table('medication_adherence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_adherence', schema=None) as batch_op:
        batch_op.create_index('idx_adherence_medication_scheduled', ['medication_id', 'scheduled_datetime'], unique=False)

    op.create_table('sensor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.Integer(), nullable=False),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('freefall_detected', sa.Boolean(), nullable=True),
    sa.Column('inactivity_detected', sa.Boolean(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('spo2_percent', sa.Integer(), nullable=True),
    sa.Column('pacing_index', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_records', schema=None) as batch_op:
        batch_op.create_index('idx_sensor_device_timestamp', ['device_id', 'timestamp_utc'], unique=False)
        batch_op.create_index('idx_sensor_received_at', ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_records', schema=None) as batch_op:
        batch_op.drop_index('idx_sensor_received_at')
        batch_op.drop_index('idx_sensor_device_timestamp')

    op.drop_table('sensor_records')
    with op.batch_alter_table('medication_adherence', schema=None) as batch_op:
        batch_op.drop_index('idx_adherence_medication_scheduled')

    op.drop_table('medication_adherence')
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_emergency_responded')
        batch_op.drop_index('idx_emergency_device_timestamp')

    op.drop_table('emergency_alerts')
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_stats_device_date')

    op.drop_table('daily_statistics')
    with op.batch_alter_table('anomaly_detections', schema=None) as batch_op:
        batch_op.drop_index('idx_anomaly_device_datetime')

    op.drop_table('anomaly_detections')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_severity_read')
        batch_op.drop_index('idx_alert_device_created')

    op.drop_table('alerts')
    with op.batch_alter_table('activity_windows', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_device_date')

    op.drop_table('activity_windows')
    op.drop_table('personalized_thresholds')
    op.drop_table('patient_caregivers')
    op.drop_table('medications')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('idx_device_patient_id')

    op.drop_table('devices')
    op.drop_table('consent_records')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user_created')
        batch_op.drop_index('idx_audit_resource')

    op.drop_table('audit_log')
    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('idx_patient_uuid')

    op.drop_table('patients')
    # ### end Alembic commands ###
